spring:
  application:
    name: Itau Bank Transfer API

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    com.itau.banking.transfer_api: INFO
  file:
    name: logs/application.log

resilience4j:
  circuitbreaker:
    instances:
      notifyBacen:
        sliding-window-size: 500
        permitted-number-of-calls-in-same-window: 100
        failure-rate-threshold: 60
        wait-duration-in-open-state: 30000
        minimum-number-of-calls: 50

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      enabled: true
